# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-31 13:33
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='zakah_register_c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving', models.IntegerField()),
                ('zakah', models.FloatField()),
                ('saving_day', models.DateField()),
                ('start_day', models.DateField(default=datetime.date(1111, 1, 1))),
                ('deserve_day', models.DateField(default=datetime.date(1111, 1, 1))),
                ('active_saving', models.FloatField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='zakah_summary_c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_saving', models.IntegerField()),
                ('nesab_day', models.DateField(default=datetime.date(1111, 1, 1))),
                ('required_zakah', models.FloatField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
