# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-26 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakah_register_c',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
