# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-31 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakah_summary_c',
            name='total_saving',
            field=models.IntegerField(default=0),
        ),
    ]
