# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-27 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah1', '0002_zakah_register_c_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakah_register_c',
            name='active',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='zakah_summary_c',
            name='required_zakah',
            field=models.FloatField(),
        ),
    ]
