# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-27 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah1', '0003_auto_20200528_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakah_register_c',
            name='active_saving',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='zakah_register_c',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
