# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-05 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah1', '0003_auto_20200531_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakah_register_c',
            name='nesab_acheived',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='zakah_register_c',
            name='saving_day',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='zakah_summary_c',
            name='required_zakah',
            field=models.FloatField(default=0),
        ),
    ]
