# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-05 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah1', '0004_auto_20200605_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakah_register_c',
            name='saving_day',
            field=models.DateField(),
        ),
    ]
