# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-28 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah1', '0005_auto_20200528_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakah_register_c',
            name='deserve_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='zakah_register_c',
            name='start_day',
            field=models.DateField(),
        ),
    ]
