# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-11 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah1', '0005_auto_20200605_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakah_register_c',
            name='net_save_increase',
            field=models.FloatField(default=0),
        ),
    ]
