# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-28 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakah1', '0006_auto_20200528_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakah_register_c',
            name='active',
        ),
        migrations.RemoveField(
            model_name='zakah_register_c',
            name='active_saving',
        ),
        migrations.RemoveField(
            model_name='zakah_register_c',
            name='deserve_day',
        ),
        migrations.RemoveField(
            model_name='zakah_register_c',
            name='saving',
        ),
        migrations.RemoveField(
            model_name='zakah_register_c',
            name='saving_day',
        ),
        migrations.RemoveField(
            model_name='zakah_register_c',
            name='start_day',
        ),
        migrations.RemoveField(
            model_name='zakah_register_c',
            name='zakah',
        ),
        migrations.RemoveField(
            model_name='zakah_summary_c',
            name='required_zakah',
        ),
        migrations.RemoveField(
            model_name='zakah_summary_c',
            name='total_saving',
        ),
    ]
