# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-28 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah1', '0008_remove_zakah_summary_c_nesab_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakah_register_c',
            name='saving',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
