# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-28 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakah1', '0009_zakah_register_c_saving'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakah_register_c',
            name='username',
        ),
        migrations.RemoveField(
            model_name='zakah_summary_c',
            name='username',
        ),
        migrations.DeleteModel(
            name='zakah_register_c',
        ),
        migrations.DeleteModel(
            name='zakah_summary_c',
        ),
    ]
