# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-28 20:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah1', '0011_zakah_register_c_zakah_summary_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zakah_summary_c',
            old_name='equired_zakah',
            new_name='required_zakah',
        ),
        migrations.AlterField(
            model_name='zakah_register_c',
            name='deserve_day',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='zakah_register_c',
            name='saving_day',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='zakah_register_c',
            name='start_day',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='zakah_summary_c',
            name='nesab_day',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
