# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-29 13:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah1', '0013_auto_20200528_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakah_register_c',
            name='deserve_day',
            field=models.DateField(default=datetime.date(1111, 1, 1)),
        ),
        migrations.AlterField(
            model_name='zakah_register_c',
            name='saving_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='zakah_register_c',
            name='start_day',
            field=models.DateField(default=datetime.date(1111, 1, 1)),
        ),
        migrations.AlterField(
            model_name='zakah_summary_c',
            name='nesab_day',
            field=models.DateField(default=datetime.date(1111, 1, 1)),
        ),
    ]
